FROM python:3.11

# Update packages and install additional dependencies
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install ffmpeg

# install tools just for development
RUN apt-get update
#maybe we should use a bigger distro...
RUN apt-get install -y zsh git icu-devtools adr-tools curl lsof gh
RUN pip install --upgrade pip

# Install Node.js v20.x
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs

# Set up Oh My Zsh for a better Zsh experience
RUN sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"

# Set the default shell to Zsh
SHELL ["/bin/zsh", "-c"]

WORKDIR /tmp

# install pnpm
RUN curl -fsSL https://get.pnpm.io/install.sh | SHELL=/bin/zsh sh - \
    && ln -s /root/.local/share/pnpm/pnpm /usr/local/bin/pnpm
ENV PATH="/root/.local/share/pnpm/bin:$PATH"


EXPOSE 8787
